# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Tripal Crop Docker
tagline:          'Our tools at your fingertips!'
description:      'A fully provisioned Tripal site aimed at supporting crop-focused and breeding research.'
url:              https://www.divseekcanada.ca/tripal-crop-docker
baseurl:

author:
  name:           'Lacey-Anne Sanderson'
  url:            https://github.com/laceysanderson

collections:
  docs:
    output: true

# Custom vars
version:          7.x-1.3

github:
  repo:           https://github.com/divseek-canada/tripal-crop-docker
